# Generated by Django 4.2.5 on 2023-09-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('empresaAsociada', models.CharField(default='DEFAULT VALUE', max_length=200)),
            ],
            options={
                'db_table': 'categoriaservicio',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcliente', models.IntegerField(default='DEFAULT VALUE', max_length=100)),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('apellido', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('correo', models.EmailField(default='DEFAULT VALUE', max_length=254)),
                ('dirrecion', models.CharField(default='DEFAULT VALUE', max_length=200)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempresa', models.IntegerField(default='DEFAULT VALUE', max_length=100)),
                ('nombreEmpresa', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('ubicacionEmpresa', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('infoEmpresa', models.CharField(default='DEFAULT VALUE', max_length=1000)),
                ('estadoEmpresa', models.BooleanField()),
                ('categoriaServicio', models.CharField(default='DEFAULT VALUE', max_length=100)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitudId', models.IntegerField(default='DEFAULT VALUE', max_length=100)),
                ('categoriaSolicitud', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('disponibilidad', models.BooleanField()),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
    ]
