# Generated by Django 4.2.5 on 2023-10-16 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('apellido', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('telefono', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('correo', models.EmailField(default='DEFAULT VALUE', max_length=254)),
                ('contraseña', models.CharField(default='DEFAULT VALUE', max_length=100)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('infoEmpresa', models.CharField(default='DEFAULT VALUE', max_length=1000)),
                ('ubicacionEmpresa', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('contactoEmpresa', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('horario', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('estadoEmpresa', models.BooleanField(default=False)),
                ('contraseña', models.CharField(default='DEFAULT VALUE', max_length=100)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('descripcionServicio', models.CharField(default='DEFAULT VALUE', max_length=1000)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastFix_app.empleado')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Reserva_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastFix_app.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastFix_app.servicio')),
            ],
            options={
                'db_table': 'reserva_servicio',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastFix_app.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastFix_app.empleado')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
