# Generated by Django 4.2.5 on 2023-09-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastFix_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idcliente',
            field=models.IntegerField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='idempresa',
            field=models.IntegerField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solicitudId',
            field=models.IntegerField(default='DEFAULT VALUE'),
        ),
    ]
